<a href="https://colab.research.google.com/github/Sourav-Manik/Data-Science-Assignment/blob/main/Assignment_10_Recommendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv('/content/book.csv',encoding = 'unicode_escape')

In [3]:
df[0:5]

   Unnamed: 0  ...  Book.Rating
0           1  ...            5
1           2  ...            3
2           3  ...            6
3           4  ...            8
4           5  ...            6

[5 rows x 4 columns]

In [4]:
df=df.drop('Unnamed: 0',axis=1)

In [5]:
#rename the columns
df = df.rename({'User.ID': 'UserID','Book.Title': 'Title','Book.Rating': 'Rating' }, axis=1)

In [6]:
df.head()

   UserID                                              Title  Rating
0  276726                                Classical Mythology       5
1  276729                                       Clara Callan       3
2  276729                               Decision in Normandy       6
3  276736  Flu: The Story of the Great Influenza Pandemic...       8
4  276737                             The Mummies of Urumchi       6

In [7]:
df.shape

(10000, 3)

In [8]:
#number of unique users in the dataset
len(df.UserID.unique())

2182

In [9]:
len(df.Title.unique())

9659

In [10]:
df = df.drop_duplicates()

In [11]:
df.shape

(9998, 3)

In [13]:
user_book_df = df.pivot_table(index='UserID',
                        columns='Title',
                        values='Rating').reset_index(drop=True)

In [14]:
user_book_df

Title   Jason, Madison &amp  ...  Ã?Â?bermorgen.
0                       NaN  ...             NaN
1                       NaN  ...             NaN
2                       NaN  ...             NaN
3                       NaN  ...             NaN
4                       NaN  ...             NaN
...                     ...  ...             ...
2177                    NaN  ...             NaN
2178                    NaN  ...             NaN
2179                    NaN  ...             NaN
2180                    NaN  ...             NaN
2181                    NaN  ...             NaN

[2182 rows x 9659 columns]

In [15]:
user_book_df.index = df.UserID.unique()

In [16]:
user_book_df

Title    Jason, Madison &amp  ...  Ã?Â?bermorgen.
276726                   NaN  ...             NaN
276729                   NaN  ...             NaN
276736                   NaN  ...             NaN
276737                   NaN  ...             NaN
276744                   NaN  ...             NaN
...                      ...  ...             ...
162107                   NaN  ...             NaN
162109                   NaN  ...             NaN
162113                   NaN  ...             NaN
162121                   NaN  ...             NaN
162129                   NaN  ...             NaN

[2182 rows x 9659 columns]

In [17]:
user_book_df.shape

(2182, 9659)

In [18]:
#Impute those NaNs with 0 values
user_book_df.fillna(0, inplace=True)

In [20]:
user_book_df.head()

Title    Jason, Madison &amp  ...  Ã?Â?bermorgen.
276726                   0.0  ...             0.0
276729                   0.0  ...             0.0
276736                   0.0  ...             0.0
276737                   0.0  ...             0.0
276744                   0.0  ...             0.0

[5 rows x 9659 columns]

In [21]:
#Calculating Cosine Similarity between Users
from sklearn.metrics import pairwise_distances
from scipy.spatial.distance import cosine, correlation

In [22]:
user_sim = 1 - pairwise_distances( user_book_df.values,metric='cosine')

In [23]:
user_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [24]:
#Store the results in a dataframe
user_sim_df = pd.DataFrame(user_sim)

In [25]:
user_sim_df.head()

   0     1     2     3     4     5     ...  2176  2177  2178  2179  2180  2181
0   1.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
1   0.0   1.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
2   0.0   0.0   1.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
3   0.0   0.0   0.0   1.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
4   0.0   0.0   0.0   0.0   1.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0

[5 rows x 2182 columns]

In [26]:
#Set the index and column names to user ids 
user_sim_df.index = df.UserID.unique()
user_sim_df.columns = df.UserID.unique()

In [27]:
user_sim_df.iloc[0:5, 0:5]

        276726  276729  276736  276737  276744
276726     1.0     0.0     0.0     0.0     0.0
276729     0.0     1.0     0.0     0.0     0.0
276736     0.0     0.0     1.0     0.0     0.0
276737     0.0     0.0     0.0     1.0     0.0
276744     0.0     0.0     0.0     0.0     1.0

In [28]:
np.fill_diagonal(user_sim, 0)
user_sim_df.iloc[0:5, 0:5]

        276726  276729  276736  276737  276744
276726     0.0     0.0     0.0     0.0     0.0
276729     0.0     0.0     0.0     0.0     0.0
276736     0.0     0.0     0.0     0.0     0.0
276737     0.0     0.0     0.0     0.0     0.0
276744     0.0     0.0     0.0     0.0     0.0

In [29]:
#Most Similar Users
user_sim_df.idxmax(axis=1)[0:5]

276726    276726
276729    276726
276736    276726
276737    276726
276744    276726
dtype: int64

In [30]:
df[(df['UserID']==276726) | (df['UserID']==276737)]

   UserID                   Title  Rating
0  276726     Classical Mythology       5
4  276737  The Mummies of Urumchi       6

In [31]:
user_1=df[df['UserID']==276726]

In [32]:
user_2=df[df['UserID']==276737]

In [33]:
user_2.Title

4    The Mummies of Urumchi
Name: Title, dtype: object

In [34]:
user_1.Title

0    Classical Mythology
Name: Title, dtype: object

In [35]:
pd.merge(user_1,user_2,on='Title',how='outer')

   UserID_x                   Title  Rating_x  UserID_y  Rating_y
0  276726.0     Classical Mythology       5.0       NaN       NaN
1       NaN  The Mummies of Urumchi       NaN  276737.0       6.0